"""Реэкспорт схем. Из них же генерируются типы для фронта."""

from app.schemas.ai import (
    AIClarifyQuestion,
    AIClarifyResult,
    AICriteriaResult,
    AIDay,
    AIDayBatch,
    AIPhase,
    AIRouteSkeleton,
    AISimplifiedTask,
    TokenUsage,
)
from app.schemas.goal import (
    ClarifyAnswer,
    ClarifyQuestion,
    ClarifyRequest,
    ClarifyResponse,
    CriteriaUpdate,
    CriterionOut,
    GoalCreate,
    GoalDetail,
    GoalDraftOut,
    GoalListItem,
    GenerateRequest,
    PhaseOut,
)
from app.schemas.task import (
    ChecklistItemOut,
    ChecklistItemUpdate,
    CompleteDayOut,
    CompleteDayRequest,
    DailyTaskOut,
    TodayOut,
)
from app.schemas.user import SessionRequest, UserOut

__all__ = [
    "AIClarifyQuestion",
    "AIClarifyResult",
    "AICriteriaResult",
    "AIDay",
    "AIDayBatch",
    "AIPhase",
    "AIRouteSkeleton",
    "AISimplifiedTask",
    "ChecklistItemOut",
    "ChecklistItemUpdate",
    "ClarifyAnswer",
    "ClarifyQuestion",
    "ClarifyRequest",
    "ClarifyResponse",
    "CompleteDayOut",
    "CompleteDayRequest",
    "CriteriaUpdate",
    "CriterionOut",
    "DailyTaskOut",
    "GoalCreate",
    "GoalDetail",
    "GenerateRequest",
    "GoalDraftOut",
    "GoalListItem",
    "PhaseOut",
    "SessionRequest",
    "TodayOut",
    "TokenUsage",
    "UserOut",
]
